# Question 0 - RECS and Replicate Weights [15 points]

In [10]:
import pandas as pd

## Data Files
Three data files are needed:

- 2015 RECS microdata files:
https://www.eia.gov/consumption/residential/data/2015/csv/recs2015_public_v4.csv
- 2009 RECS microdata files:
https://www.eia.gov/consumption/residential/data/2009/csv/recs2009_public.csv
- 2009 data year the replicate weights file:
https://www.eia.gov/consumption/residential/data/2009/csv/recs2009_public_repweights.csv

In [16]:
base_url = "https://www.eia.gov/consumption/residential/data/"

In [17]:
## get link from the website
url_2015 = base_url + "2015/csv/recs2015_public_v4.csv"
## read the csv file
df_2015 = pd.read_csv(url_2015)
## make column names in lower case and display year 2015 recs file
df_2015 = df_2015.rename(columns=str.lower)
df_2015

,doeid,regionc,division,metromicro,uatyp10,typehuq,ztypehuq,cellar,zcellar,basefin,...,zelamount,ngxbtu,periodng,zngamount,foxbtu,periodfo,zfoamount,lpxbtu,periodlp,zlpamount
0,10001,4,10,METRO,U,2,0,0,0,-2,...,0,103.32,1,0,137.45,-2,-2,91.33,-2,-2
1,10002,3,7,NONE,R,2,0,0,0,-2,...,1,NaN,-2,-2,137.45,-2,-2,91.33,-2,-2
2,10003,3,6,METRO,U,2,0,1,0,1,...,0,100.14,1,0,137.45,-2,-2,91.33,-2,-2
3,10004,2,4,MICRO,C,2,0,1,0,1,...,0,NaN,-2,-2,137.45,-2,-2,91.33,2,0
4,10005,1,2,METRO,U,2,0,1,0,0,...,0,102.83,1,0,137.45,-2,-2,91.33,-2,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5681,15682,2,3,METRO,U,5,0,-2,-2,-2,...,1,102.40,5,1,137.45,-2,-2,91.33,-2,-2
5682,15683,3,6,MICRO,C,2,0,0,0,-2,...,0,99.34,1,0,137.45,-2,-2,91.33,-2,-2
5683,15684,2,3,METRO,U,5,0,-2,-2,-2,...,0,NaN,-2,-2,137.45,-2,-2,91.33,-2,-2
5684,15685,3,7,METRO,R,2,0,0,0,-2,...,0,NaN,-2,-2,137.45,-2,-2,91.33,-2,-2
5685,15686,2,3,METRO,U,4,0,-2,-2,-2,...,0,NaN,-2,-2,137.45,-2,-2,91.33,-2,-2

In [18]:
## get link from the website
url_2009 = base_url + "2009/csv/recs2009_public.csv"
## read the csv file
df_2009 = pd.read_csv(url_2009)
## make column names in lower case and display year 2009 recs file
df_2009 = df_2009.rename(columns=str.lower)
df_2009

/Users/ShuyanLi/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3296: DtypeWarning: Columns (717,718) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,doeid,regionc,division,reportable_domain,typehuq,nweight,hdd65,cdd65,hdd30yr,cdd30yr,...,scaleker,iecc_climate_pub,hdd50,cdd80,gnd_hdd65,wsf,oa_lat,gwt,designdbt99,designdbt1
0,1,2,4,12,2,2471.68,4742,1080,4953,1271,...,-2,4A,2117,56,4250,0.48,6,56,9,96
1,2,4,10,26,2,8599.17,2662,199,2688,143,...,-2,3C,62,26,2393,0.61,0,64,38,73
2,3,1,1,1,5,8969.92,6233,505,5741,829,...,-2,5A,2346,49,5654,0.48,3,52,12,88
3,4,2,3,7,2,18003.64,6034,672,5781,868,...,-2,5A,2746,0,4941,0.55,4,55,7,87
4,5,1,1,1,3,5999.61,5388,702,5313,797,...,-2,5A,2251,0,5426,0.61,4,50,13,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12078,12079,2,3,9,2,10219.80,7671,332,7784,451,...,-2,6A-6B,4289,39,7819,0.59,0,48,-3,84
12079,12080,3,7,21,4,8689.07,2085,2844,2520,2286,...,-2,3B-4B,360,393,1869,0.50,0,56,26,101
12080,12081,2,4,10,2,4697.21,7935,472,8074,600,...,-2,6A-6B,4494,22,8477,0.58,1,46,-9,89
12081,12082,4,8,23,2,13155.68,5834,770,5989,957,...,-2,5B-5C,2840,0,9010,0.54,1,53,13,93
12082,12083,4,10,26,2,7703.43,2806,124,2859,139,...,-2,3C,92,0,3048,0.53,0,60,44,75

In [19]:
## get link from the website
url_2009_weight = base_url + "2009/csv/recs2009_public_repweights.csv"
## read the csv file
df_2009_weight = pd.read_csv(url_2009_weight)
## make column names in lower case and display year 2009 recs weight file
df_2009_weight = df_2009_weight.rename(columns=str.lower)
df_2009_weight

,doeid,nweight,brr_weight_1,brr_weight_2,brr_weight_3,brr_weight_4,brr_weight_5,brr_weight_6,brr_weight_7,brr_weight_8,...,brr_weight_235,brr_weight_236,brr_weight_237,brr_weight_238,brr_weight_239,brr_weight_240,brr_weight_241,brr_weight_242,brr_weight_243,brr_weight_244
0,1,2471.679705,3628.305158,1392.373673,1271.181424,3528.052756,3478.045539,1164.560766,1215.035282,1204.172316,...,1390.318940,1134.968007,1195.730023,1304.300183,1248.137817,1230.150977,1157.195411,1156.412430,1240.217824,3655.101693
1,2,8599.172010,4408.308000,4247.696575,4450.561135,13207.910560,4178.691121,4271.613426,4219.739488,4229.454405,...,12811.288200,4236.006271,12779.722250,12680.646870,13172.272250,13656.849190,4246.979562,13134.213440,12624.316870,12846.242170
2,3,8969.915921,13664.732100,13655.213030,4359.190122,13086.068610,13721.970010,13459.082130,4749.199418,4689.040317,...,12170.897940,12829.708110,13637.133920,13098.702000,12569.565770,14155.301240,5008.801785,5256.419281,13201.724800,4812.600110
3,4,18003.639600,9456.435434,25723.464490,25125.994190,9334.577574,28340.387380,8659.271182,9079.577826,9200.147549,...,8519.486929,24214.978000,9840.195847,26856.650810,25453.890870,8483.396618,26383.441980,26510.027830,27188.612470,9534.025088
4,5,5999.605242,8659.554041,3269.734038,2910.690905,2798.774832,8544.785536,3091.628917,2939.910109,3251.644196,...,2648.413487,7770.479222,3206.892604,8274.644460,2920.173900,3005.523507,9469.217579,3427.954293,3218.392309,3251.371247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12078,12079,10219.802880,4971.444986,5118.738130,16323.838600,16114.371840,15516.980350,4729.643641,14820.087660,15909.196600,...,4641.168902,15373.360120,5398.060666,5190.461411,14353.431130,4458.883796,16606.352160,15397.944010,15886.510090,15669.237850
12079,12080,8689.074445,13379.958700,12643.430680,4925.686838,3901.787982,4453.946818,4518.165817,13984.737830,12786.838190,...,13724.315210,4774.309762,4421.945515,13766.511860,12309.989790,12649.677120,13862.104570,4383.465655,13033.819830,3976.693639
12080,12081,4697.213624,2344.955794,7032.330646,2361.206603,7039.214013,2445.940157,2271.017810,6699.021505,7028.675252,...,2405.426480,6985.802482,6828.306201,2382.442743,2376.716399,2352.500819,6853.585876,2272.806556,6854.803388,2479.082636
12081,12082,13155.678790,6701.717641,7013.500661,6372.473843,6930.883853,6899.686416,6467.124670,19294.640290,6433.589904,...,6547.815677,6959.110117,19090.172760,6699.440676,6687.420209,20062.409940,20375.068830,19478.810910,6721.075376,17663.466590
12082,12083,7703.426315,3949.109962,11415.686600,3986.961736,11832.088680,3743.411471,3826.654385,3780.183973,3788.886921,...,3825.593695,11384.268910,3816.167748,3786.582734,11800.162680,4078.087647,11413.759630,3922.022777,3769.761968,3836.031339

## Variables
Requirement:
Using the codebooks for the assoicated data files, determine what variables you will need to answer the following question. Be sure to include variables like the unit id and sample weights.

Question: Estimate the average number of heating and cooling degree days for residences in each Census region for both 2009 and 2015.

In [14]:
## There are five variables we are interested related to this question:
## 'DOEID', 'REGIONC', 'HDD65', 'CDD65', 'NWEIGHT'
## Then, we create two new dataframes to store these variables for year 2009 and 2015
df_2009_new = df_2009[['doeid', 'regionc', 'hdd65', 'cdd65', 'nweight']]
df_2015_new = df_2015[['doeid', 'regionc', 'hdd65', 'cdd65', 'nweight']]

## Weights and Replicate Weights

1. Find a link explaining how to use the replicate weights:
https://www.eia.gov/consumption/residential/methodology/2009/pdf/using-microdata-022613.pdf

2. Briefly explain how the replicate weights are used to estimate standard errors for weighted point estimates:

In your explanation please retype the key equation making sure to document what each variable in the equation is. Don’t forget to include the Fay coefficient and its value(s) for the specific replicate weights included with the survey data.

First, this method roots in Fay’s method of the balanced repeated replication (BRR) technique. This method uses replicate weights to repeatedly estimate the statistic of interest and calculate the differences between these estimates and the full-sample estimate.</br>

The variance of $\hat\theta$ is estimated by:

$$\hat{V}(\tilde{\theta})={\frac{1}{R(1-\epsilon)^2}}\displaystyle \sum^{R}_{r=1}{(\hat\theta_r - \hat\theta)^2}$$

- $\theta$ is a population parameter of interest
- $\hat\theta$ is the estimate from the full sample for $\theta$
- $\hat\theta_r$ is the estimate from the r-th replicate subsample by using replicate weights
- $\epsilon$ is the Fay coefficient, $0≤\epsilon<1$.

For the 2009 RECS, R=244(the number of replicate subsamples) and $\epsilon=.5$.

For the 2015 RECS, R=96(the number of replicate subsamples) and $\epsilon=.5$.

The formula for calculating the esitimated standard error is:
$$\sqrt{\hat{V}(\tilde{\theta})}$$